### ISSUE TITLE
"Cannot call method 'parse' of undefined" in CUBRIDConnection.js:1333:20

### ISSUE THREAD

**Issue by kadishmal** [CUBRID/node-cubrid#33]
Migrated from http://jira.cubrid.org/browse/APIS-527.

After having updated node-cubrid to 2.0.1, the following error is thrown:

	Connected
	Executing: SELECT * FROM tbl_posts /*+ shard_id(0) */
	Number of columns: 4
	post_id(Int), title(String), content(Varbit), post_date(Int)
	Shard(0) holds 0 records
	[Error: AutoCommitMode is enabled! - denying commit request.]

	C:\Users\nhn\Documents\vagrant\cubrid-shard\nodejs\node_modules\node-cubrid\src\CUBRIDConnection.js:1333
	      commitPacket.parse(packetReader);
	                   ^
	TypeError: Cannot call method 'parse' of undefined
	    at Socket.<anonymous> (C:\Users\nhn\Documents\vagrant\cubrid-shard\nodejs\node_modules\node-cubrid\src\CUBRIDConnection.js:1333:20)
	    at Socket.EventEmitter.emit (events.js:117:20)
	    at Socket.<anonymous> (_stream_readable.js:699:14)
	    at Socket.EventEmitter.emit (events.js:92:17)
	    at emitReadable_ (_stream_readable.js:382:10)
	    at emitReadable (_stream_readable.js:377:5)
	    at readableAddChunk (_stream_readable.js:142:7)
	    at Socket.Readable.push (_stream_readable.js:112:10)
	    at TCP.onread (net.js:511:21)

The code under question is:

	CUBRIDConnection.prototype.commit = function (callback) {
	...
	  if (self.autoCommitMode === false) {
	    var packetWriter = new PacketWriter();
	    var commitPacket = new CommitPacket(
	      {
	        casInfo    : self._CASInfo,
	        db_version : self._DB_ENGINE_VER
	      }
	    );
	    commitPacket.write(packetWriter);
	    self._socket.write(packetWriter._buffer);
	  } else {
	    self._socket.removeAllListeners('data');
	    err = new Error(ErrorMessages.ERROR_NO_COMMIT);
	    Helpers._emitEvent(self, err, self.EVENT_ERROR, null);
	    if (callback && typeof(callback) === 'function') {
	      callback.call(self, err);
	    }
	  }

	  self._socket.on('data', function (data) {
	    ...
	    if (responseData.length === expectedResponseLength) {
	      ...
	      commitPacket.parse(packetReader);

The last line is called, however, `commitPacket` is not defined because `if (self.autoCommitMode === false) {` condition is not satisfied.

The same `SELECT` code from APIS-521 can be used to replicate this error.

Let me know if you cannot replicate. I will provide more examples.

**Comment by kadishmal** [comment]
Fixed in [v2.0.2](https://github.com/CUBRID/node-cubrid/releases/tag/v2.0.2) release.
